# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glance < Formula
  desc "Glance is a specialized MITM proxy for AI Agents and developers."
  homepage "https://github.com/wahyudotdev/glance"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wahyudotdev/glance/releases/download/v0.1.4/glance_Darwin_x86_64.tar.gz"
      sha256 "d00414238db23e4d520dc8e5aade5e24f9a1021a31b8e9ed2dc5e201ebeb55bb"

      def install
        bin.install "glance"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wahyudotdev/glance/releases/download/v0.1.4/glance_Darwin_arm64.tar.gz"
      sha256 "5aed27d8604a1c318138da4b2f2fe20c66ea9460887e9dedb95cc21c215cf1d3"

      def install
        bin.install "glance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wahyudotdev/glance/releases/download/v0.1.4/glance_Linux_x86_64.tar.gz"
      sha256 "ddfd5eb139de3080aedbbbc2e41cd8f83fbdcb6be61b7461b1bbdc6dc90ae78e"
      def install
        bin.install "glance"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wahyudotdev/glance/releases/download/v0.1.4/glance_Linux_arm64.tar.gz"
      sha256 "b79fc1776b5f0c8cf43b5cf24134d44107f92f19b8484269ed1b609a047f887f"
      def install
        bin.install "glance"
      end
    end
  end

  test do
    system "#{bin}/glance --version"
  end
end
